<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="submission-update-view-state" :state="state" hideable="true" backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <form @submit.prevent="submit">
        <div class="row">
          <div class="col-xs-12">
            <div v-for="(value, key) in submission" :key="key">
              <template v-if="isObject(value)">
                <div>{{ key }}:</div>
                <div class="indent">
                  <NestedObject :data="value" />
                </div>
              </template>
              <template v-else-if="Array.isArray(value)">
                <div>{{ key }}:</div>
                <div class="indent">
                  <ul>
                    <li v-for="(item, index) in value" :key="index">
                      <template v-if="isObject(item)">
                        <NestedObject :data="item" />
                      </template>
                      <template v-else>{{ item }}</template>
                    </li>
                  </ul>
                </div>
              </template>
              <template v-else>
                <div>{{ key }}: {{ value }}</div>
              </template>
            </div>
          </div>
        </div>
        <div class="modal-actions">       
          <button type="button" class="btn btn-link"  @click="$emit('hide')">
            {{ $t('action.neverMind') }}
          </button>
        </div>
      </form>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';
import MarkdownTextarea from '../markdown/textarea.vue';

import useRequest from '../../composables/request';
import useViewState from '../../composables/view-state';

import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

const selectableStates = ['approved', 'hasIssues', 'rejected'];

export default {
  name: 'SubmissionUpdateViewState',
  components: { Modal, Spinner, MarkdownTextarea, NestedObject: {
      props: ['data'],
      template: `
        <div>
          <div v-for="(value, key) in data" :key="key">
            <template v-if="typeof value === 'object' && value !== null">
              <div>{{ key }}:</div>
              <div class="indent">
                <NestedObject :data="value" />
              </div>
            </template>
            <template v-else>
              <div>{{ key }}: {{ value }}</div>
            </template>
          </div>
        </div>
      `,
    } },
  props: {
    state: Boolean,
    projectId: {
      type: String,
      required: true
    },
    xmlFormId: {
      type: String,
      required: true
    },
    submission: Object
  },
  emits: ['hide'],
  setup() {
    const { request, awaitingResponse } = useRequest();
    const { viewStateC } = useViewState();
    return { request, awaitingResponse, viewStateC };
  },
  watch: {
    state(state) {
     
    }
  },
  methods: {
    submit() {
      this.$emit('hide');
    },
    isObject(value) {
      return value && typeof value === 'object' && !Array.isArray(value);
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/variables';
.indent {
  margin-left: 20px;
}
#submission-update-view-state {
  .form-group {
    margin-bottom: 0;
  }

  $margin-left-icon: 2px;

  .icon-comments {
    margin-left: $margin-left-icon;
    margin-right: $margin-right-icon;
  }

  .icon-check-circle,
  .icon-times-circle {
    margin-left: #{$margin-left-icon + 1px};
    margin-right: #{$margin-right-icon + 1px};
  }

  .icon-check-circle {
    color: $color-success;
  }

  .icon-comments {
    color: $color-warning;
  }

  .icon-times-circle {
    color: $color-danger;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Update Review State",
    "field": {
      "notes": "Notes and comments (optional)"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Aktualizovat stav kontroly",
    "field": {
      "notes": "Poznámky a komentáře (volitelné)"
    }
  },
  "de": {
    "title": "Überprüfungsstatus aktualisieren",
    "field": {
      "notes": "Notizen und Kommentare (optional)"
    }
  },
  "es": {
    "title": "Actualizar estado de revisión",
    "field": {
      "notes": "Notas y comentarios (opcional)"
    }
  },
  "fr": {
    "title": "Changer l'état de la soumission",
    "field": {
      "notes": "Notes et commentaires (facultatif)"
    }
  },
  "id": {
    "title": "Perbarui status ulasan",
    "field": {
      "notes": "Catatan dan komentar (opsional)"
    }
  },
  "it": {
    "title": "Aggiorna lo Stato Revisione",
    "field": {
      "notes": "Note e commenti (opzionale)"
    }
  },
  "ja": {
    "title": "レビュー・ステータスの更新",
    "field": {
      "notes": "メモとコメント（任意）"
    }
  },
  "sw": {
    "title": "Sasisha Uhakiki wa hali",
    "field": {
      "notes": "Vidokezo na maoni (si lazima)"
    }
  },
  "zh-Hant": {
    "title": "更新審核狀態",
    "field": {
      "notes": "註釋和評論（可選）"
    }
  }
}
</i18n>
